; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25017.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\alon.HOME\AppData\Local\Temp\.NETFramework,Version=4.0.AssemblyAttributes.cpp"
