; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\alon\AppData\Local\Temp\.NETFramework,Version=4.7.AssemblyAttributes.cpp"
